### ISSUE TITLE
Bulk cleanup old images

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#1040]
Should we do a bulk cleanup of the old images stored on MAR?  We have been asked in the past by MAR to cleanup old images.  We have a number of extremely old images that are good candidates.  This may make the work on adding EOL annotations to old images easier.

**Comment by lbussell** [comment]
[Triage] MAR has documentation on how to do bulk deletion of images via a json file - [[internal link]](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1024)

This repo has had a number of different tagging schemes over the years - it would be easy to come up with a query to delete all images with a known out-of-date tagging scheme. Images that are out of date from this repo should not be used.

Any images we remove should also be removed from our internal ACR.

**Comment by lbussell** [comment]
[Triage] Closing this since we've changed our ACR cleanup policy to clean up EOL images after a certain period of time: https://github.com/dotnet/docker-tools/pull/1384. There's no more work to be done with cleaning up out of date images from our ACR.

We can re-open this/reconsider deleting EOL images from MAR if they ever ask us do to this again.
