### ISSUE TITLE
Fedora Dockerfile uses obsolete RID

### ISSUE THREAD

**Issue by ggobbe** [dotnet/dotnet-buildtools-prereqs-docker#121]
Fedora 28 and 29 are still using the old Ubuntu 14.04 `__PUBLISH_RID`
- https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/fedora/28/Dockerfile
- https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/fedora/29/Dockerfile

Could they be updated to something more relevant?

Also, what is the `__PUBLISH_RID` used for?

Thanks

**Comment by MichaelSimons** [comment]
@ianhays - Can the `__PUBLISH_RID` get updated now?  Is this something you can make a PR for?

**Comment by MichaelSimons** [comment]
@ianhays - ping.

**Comment by MichaelSimons** [comment]
@MattGal - Can you answer the question of how the builds are using the `__PUBLISH_RID` ENV within the Docker images?

**Comment by MattGal** [comment]
@MichaelSimons I tried to get an answer on this in the past but sadly still don't know; I'm asking around.

**Comment by MattGal** [comment]
Chatted with @joperezr and noted a couple things:

- As far as either of us can tell this is not used in anyone's builds
- We only build on RHEL7, RHEL6, and Alpine docker images any more, none of which have the variable set

My conclusion here is that it's fine to remove, and if it turns out not to be we can revisit this.

**Comment by MichaelSimons** [comment]
Closing as Fedora 28 and 29 are EOL.  The Fedora 30 image no longer contains the `__PUBLISH_RID` ENV
