### ISSUE TITLE
Adjust build timeout values now that build times have improved

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#183]
Due to machine infrastructure changes, build times have improved. The timeout values should be adjusted based on the new build times to ensure we don't waste a ton of time on edge cases where the build isn't working correctly.

**Comment by MichaelSimons** [comment]
The `Centos 6`, `Centos 7`, and `Ubuntu 16.04` are the only legs that specify an extended timeout (120 min).  I re-ran these legs and they still require this extended timeout.  The reason these builds are not impacted significantly by the SSD change is because these Dockerfiles are source building several components (e.g. CPU intensive).
