### ISSUE TITLE
Cannot find alpine 10 image in docker hub

### ISSUE THREAD

**Issue by wli3** [dotnet/dotnet-buildtools-prereqs-docker#193]
but there is a docker file

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/alpine/3.10/helix/amd64/Dockerfile

**Comment by mthalman** [comment]
That's because there is no listing in Docker Hub for the `dotnet-buildtools/prereqs` repository.  See [here](https://github.com/dotnet/dotnet-buildtools-prereqs-docker#where-are-the-published-images) to find the image tags.  The Alpine 3.10 tag is currently `mcr.microsoft.com/dotnet-buildtools/prereqs/alpine-3.10-helix-3043688-20190918214010`.

**Comment by MichaelSimons** [comment]
Please see the [README.md](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/README.md) for more detailed info on working with the images produced from this repo.
