### ISSUE TITLE
Builds failing because of "no space left on device"

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/dotnet-buildtools-prereqs-docker#272]
After merging https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/271 I saw some of the builds now consistently failing with "no space left on device" errors.

Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=575510&view=results (I retriggered four times).

@mthalman @MichaelSimons any ideas? I assume because that build runs on the Azure Pipelines hosted pool which has limited disk space and adding one more image caused it to run out.

Can we somehow clean temporary files between each image build?

**Comment by mthalman** [comment]
I attempted to run a build on a self-hosted Linux agent that we have but that ran out of disk space as well.  Continuing to investigate.

**Comment by MichaelSimons** [comment]
@mthalman was able to workaround the disk space issue by using a different build pool with larger drive space.  You can find the new images from #271 documented at [Latest tags](https://github.com/dotnet/versions/blob/master/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json).

I found there was an issue with the rootfs cleanup logic that freed up a significant amount of space during the build.  This issue was addressed in #274.  Closing.

**Comment by akoeplinger** [comment]
Thank you 🎉
