### ISSUE TITLE
Create an alpine 3.12 image with Node

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/dotnet-buildtools-prereqs-docker#435]
Aspnetcore currently uses `alpine-3.9-WithNode-0fc54a3-20190918214015`, but 3.9 and 3.10 are now deprecated. We want to upgrade to 3.12, but there's no image with Node installed that will work for us.

CC @mthalman - if this is a quick/simple change, can you point me towards where I could do it myself?

**Comment by mthalman** [comment]
You'd basically need to follow the same pattern as is currently done for Alpine 3.9.  The existing [3.12 Helix Dockerfile](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/alpine/3.12/helix/amd64/Dockerfile) would need to be refactored so that it's split into a 3.12/amd64/Dockerfile and 3.12/helix/amd64/Dockerfile just like it's done for 3.9.  Any additional Dockerfiles requires update the [manifest.json](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/manifest.json) file. Again, just follow the same pattern as 3.9 for any changes in that file.

**Comment by wtgodbe** [comment]
Cool, I'll do that after lunch
