### ISSUE TITLE
How do I see the latest built and published image for a given Dockerfile?

### ISSUE THREAD

**Issue by dagood** [dotnet/dotnet-buildtools-prereqs-docker#69]
This is the best way I can think of right now to find the latest version of a specific image I want to use:

1. Find the dockerfile I'm interested in on GitHub.
2. Open the full list of tags (https://registry.hub.docker.com/v1/repositories/microsoft/dotnet-buildtools-prereqs/tags).
3. Search for the initial part of the name (like ubuntu-18.04) using the convention in the readme.
4. Pick the one with the latest date. Unfortunately the tags are sorted by name, and commit hash is in the name before the build date. Besides making a tool, the most efficient way I can think to do find latest is put the images in a text editor, edit out the commit, sort again, and see which image corresponds to the latest.

Is there any status on something like publishing this info to dotnet/versions or the Arcade BAR?

/cc @MichaelSimons @dleeapho

**Comment by tmat** [comment]
For devs who do not know about how we build these docker images it would be useful to have a starting page that lists [all distros and platforms Core CLR supports](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#supported-linux-versions) and where to find the latest container that we use in CI to test them.

**Comment by MichaelSimons** [comment]
I agree this would be valuable.  It is pretty low in the priority stack rank at the moment however.

**Comment by MichaelSimons** [comment]
Plan for implementation.  The build will generate the MCR tags yaml, utilize the MCR tag doc generator to create the tags details and insert this into the readme.  The build will them push the updated readme back to the repo.

**Comment by mthalman** [comment]
The original plan for this was to have the latest list of image tags listed in the readme that was automatically updated after each build.  Due to implementation complexity, we're backing off that plan to something simpler for now.  We'll instead provide a link in the readme to the [image info file](https://github.com/dotnet/versions/blob/master/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json) that contains metadata about the latest images that have been published, including the list of tags.  It is human readable and listed alphabetically by the path to the Dockerfile in the repo.
